{% set version = "1.0.6" %}

package:
  name: freexl
  version: {{ version }}

source:
  url: http://www.gaia-gis.it/gaia-sins/freexl-{{ version }}.tar.gz
  sha256: 3de8b57a3d130cb2881ea52d3aa9ce1feedb1b57b7daa4eb37f751404f90fc22
  patches:
    - patches/makefile.vc.patch
    - patches/nmake.opt.patch
    - patches/aarch64.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('freexl') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - libiconv  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libfreexl.a  # [not win]

about:
  home: https://www.gaia-gis.it/fossil/freexl/index
  license: MPL-1.1
  license_file: COPYING
  summary: Extract valid data from within an Excel

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
